version: "3"

services:
  runtime-setup:
    image: &image swift-openapi-generator:22.04-5.8
    build:
      args:
        ubuntu_version: "jammy"
        swift_version: "5.8"

  test:
    image: *image
    environment:
      - WARN_AS_ERROR_ARG=-Xswiftc -warnings-as-errors
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error
      - STRICT_CONCURRENCY_ARG=-Xswiftc -strict-concurrency=complete
  shell:
    image: *image
