version: "3"

services:

  runtime-setup:
    image: &image swift-openapi-generator:22.04-main
    build:
      args:
        base_image: "swiftlang/swift:nightly-main-jammy"

  test:
    image: *image
    environment:
      - WARN_AS_ERROR_ARG=-Xswiftc -warnings-as-errors
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error
      - STRICT_CONCURRENCY_ARG=-Xswiftc -strict-concurrency=complete
  shell:
    image: *image
