version: "3"

services:
  runtime-setup:
    image: &image swift-openapi-generator:22.04-5.8
    build:
      args:
        ubuntu_version: "jammy"
        swift_version: "5.8"

  test:
    image: *image
    environment:
      # Because OpenAPI supports deprecation, the generated code could include
      # deprecated symbols, which will produce warnings.
      #
      # We'll disable -warnings-as-errors for now and revisit this when we
      # refactor the compilation of the generated code into a separate
      # pipeline.
      #
      # - WARN_AS_ERROR_ARG=-Xswiftc -warnings-as-errors
      
      # SwiftSyntax currently imports a module it does not explicitly depend
      # on and so we must disable this for the time being.
      # - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error

      - STRICT_CONCURRENCY_ARG=-Xswiftc -strict-concurrency=complete

  shell:
    image: *image
