version: "3"

services:
  runtime-setup:
    image: &image swift-openapi-generator:22.04-5.9
    build:
      args:
        ubuntu_version: "jammy"
        swift_version: "5.9"

  test:
    image: *image
    environment:
      - WARN_AS_ERROR_ARG=-Xswiftc -warnings-as-errors
      # SwiftSyntax currently imports a module it does not explicitly depend
      # on and so we must disable this for the time being.
      # - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error
      - STRICT_CONCURRENCY_ARG=-Xswiftc -strict-concurrency=complete

  shell:
    image: *image
