version: "3"

services:

  runtime-setup:
    image: &image swift-openapi-generator:22.04-main
    build:
      args:
        base_image: "swiftlang/swift:nightly-main-jammy"

  test:
    image: *image
    environment:
      # Because OpenAPI supports deprecation, the generated code could include
      # deprecated symbols, which will produce warnings.
      #
      # We'll disable -warnings-as-errors for now and revisit this when we
      # refactor the compilation of the generated code into a separate
      # pipeline.
      #
      # - WARN_AS_ERROR_ARG=-Xswiftc -warnings-as-errors
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error

  shell:
    image: *image
