// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
extension Operations {
    /// List all pets
    ///
    /// You can fetch
    /// all the pets here
    ///
    /// - Remark: HTTP `GET /pets`.
    /// - Remark: Generated from `#/paths//pets/get(listPets)`.
    public enum ListPets {
        public static let id: Swift.String = "listPets"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/pets/GET/query`.
            public struct Query: Sendable, Hashable {
                /// How many items to return at one time (max 100)
                ///
                /// - Remark: Generated from `#/paths/pets/GET/query/limit`.
                public var limit: Swift.Int32?
                /// - Remark: Generated from `#/paths/pets/GET/query/habitat`.
                @frozen public enum HabitatPayload: String, Codable, Hashable, Sendable, CaseIterable {
                    case water = "water"
                    case land = "land"
                    case air = "air"
                    case _empty_ = ""
                }
                /// - Remark: Generated from `#/paths/pets/GET/query/habitat`.
                public var habitat: Operations.ListPets.Input.Query.HabitatPayload?
                /// - Remark: Generated from `#/paths/pets/GET/query/FeedsPayload`.
                @frozen public enum FeedsPayloadPayload: String, Codable, Hashable, Sendable, CaseIterable {
                    case omnivore = "omnivore"
                    case carnivore = "carnivore"
                    case herbivore = "herbivore"
                }
                /// - Remark: Generated from `#/paths/pets/GET/query/feeds`.
                public typealias FeedsPayload = [Operations.ListPets.Input.Query.FeedsPayloadPayload]
                /// - Remark: Generated from `#/paths/pets/GET/query/feeds`.
                public var feeds: Operations.ListPets.Input.Query.FeedsPayload?
                /// - Remark: Generated from `#/paths/pets/GET/query/sort`.
                public struct SortPayload: Codable, Hashable, Sendable {
                    /// - Remark: Generated from `#/paths/pets/GET/query/sort/id`.
                    public var id: Swift.String
                    /// - Remark: Generated from `#/paths/pets/GET/query/sort/name`.
                    public var name: Swift.String?
                    /// Creates a new `SortPayload`.
                    ///
                    /// - Parameters:
                    ///   - id:
                    ///   - name:
                    public init(
                        id: Swift.String,
                        name: Swift.String? = nil
                    ) {
                        self.id = id
                        self.name = name
                    }
                    public enum CodingKeys: String, CodingKey {
                        case id
                        case name
                    }
                }
                /// - Remark: Generated from `#/paths/pets/GET/query/sort`.
                public var sort: Operations.ListPets.Input.Query.SortPayload?
                /// - Remark: Generated from `#/paths/pets/GET/query/filter`.
                public struct FilterPayload: Codable, Hashable, Sendable {
                    /// - Remark: Generated from `#/paths/pets/GET/query/filter/name`.
                    public var name: Swift.String
                    /// - Remark: Generated from `#/paths/pets/GET/query/filter/state`.
                    public var state: Swift.String?
                    /// Creates a new `FilterPayload`.
                    ///
                    /// - Parameters:
                    ///   - name:
                    ///   - state:
                    public init(
                        name: Swift.String,
                        state: Swift.String? = nil
                    ) {
                        self.name = name
                        self.state = state
                    }
                    public enum CodingKeys: String, CodingKey {
                        case name
                        case state
                    }
                }
                /// - Remark: Generated from `#/paths/pets/GET/query/filter`.
                public var filter: Operations.ListPets.Input.Query.FilterPayload
                /// Supply this parameter to filter pets born since the provided date.
                ///
                /// - Remark: Generated from `#/paths/pets/GET/query/since`.
                public var since: Components.Parameters.Query_bornSince?
                /// Creates a new `Query`.
                ///
                /// - Parameters:
                ///   - limit: How many items to return at one time (max 100)
                ///   - habitat:
                ///   - feeds:
                ///   - sort:
                ///   - filter:
                ///   - since: Supply this parameter to filter pets born since the provided date.
                public init(
                    limit: Swift.Int32? = nil,
                    habitat: Operations.ListPets.Input.Query.HabitatPayload? = nil,
                    feeds: Operations.ListPets.Input.Query.FeedsPayload? = nil,
                    sort: Operations.ListPets.Input.Query.SortPayload? = nil,
                    filter: Operations.ListPets.Input.Query.FilterPayload,
                    since: Components.Parameters.Query_bornSince? = nil
                ) {
                    self.limit = limit
                    self.habitat = habitat
                    self.feeds = feeds
                    self.sort = sort
                    self.filter = filter
                    self.since = since
                }
            }
            public var query: Operations.ListPets.Input.Query
            /// - Remark: Generated from `#/paths/pets/GET/header`.
            public struct Headers: Sendable, Hashable {
                /// Request identifier
                ///
                /// - Remark: Generated from `#/paths/pets/GET/header/My-Request-UUID`.
                public var myRequestUUID: Swift.String?
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.ListPets.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - myRequestUUID: Request identifier
                ///   - accept:
                public init(
                    myRequestUUID: Swift.String? = nil,
                    accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.ListPets.AcceptableContentType>] = .defaultValues()
                ) {
                    self.myRequestUUID = myRequestUUID
                    self.accept = accept
                }
            }
            public var headers: Operations.ListPets.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - query:
            ///   - headers:
            public init(
                query: Operations.ListPets.Input.Query,
                headers: Operations.ListPets.Input.Headers = .init()
            ) {
                self.query = query
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/pets/GET/responses/200/headers`.
                public struct Headers: Sendable, Hashable {
                    /// Response identifier
                    ///
                    /// - Remark: Generated from `#/paths/pets/GET/responses/200/headers/My-Response-UUID`.
                    public var myResponseUUID: Swift.String
                    /// A description here.
                    ///
                    /// - Remark: Generated from `#/paths/pets/GET/responses/200/headers/My-Tracing-Header`.
                    public var myTracingHeader: Components.Headers.TracingHeader?
                    /// Creates a new `Headers`.
                    ///
                    /// - Parameters:
                    ///   - myResponseUUID: Response identifier
                    ///   - myTracingHeader: A description here.
                    public init(
                        myResponseUUID: Swift.String,
                        myTracingHeader: Components.Headers.TracingHeader? = nil
                    ) {
                        self.myResponseUUID = myResponseUUID
                        self.myTracingHeader = myTracingHeader
                    }
                }
                /// Received HTTP response headers
                public var headers: Operations.ListPets.Output.Ok.Headers
                /// - Remark: Generated from `#/paths/pets/GET/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/pets/GET/responses/200/content/application\/json`.
                    case json(Components.Schemas.Pets)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.Pets {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.ListPets.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - headers: Received HTTP response headers
                ///   - body: Received HTTP response body
                public init(
                    headers: Operations.ListPets.Output.Ok.Headers,
                    body: Operations.ListPets.Output.Ok.Body
                ) {
                    self.headers = headers
                    self.body = body
                }
            }
            /// A paged array of pets
            ///
            /// - Remark: Generated from `#/paths//pets/get(listPets)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.ListPets.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.ListPets.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            public struct Default: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/pets/GET/responses/default/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/pets/GET/responses/default/content/application\/json`.
                    case json(Components.Schemas._Error)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas._Error {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.ListPets.Output.Default.Body
                /// Creates a new `Default`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.ListPets.Output.Default.Body) {
                    self.body = body
                }
            }
            /// Unexpected error
            ///
            /// - Remark: Generated from `#/paths//pets/get(listPets)/responses/default`.
            ///
            /// HTTP response code: `default`.
            case `default`(statusCode: Swift.Int, Operations.ListPets.Output.Default)
            /// The associated value of the enum case if `self` is `.`default``.
            ///
            /// - Throws: An error if `self` is not `.`default``.
            /// - SeeAlso: `.`default``.
            public var `default`: Operations.ListPets.Output.Default {
                get throws {
                    switch self {
                    case let .`default`(_, response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "default",
                            response: self
                        )
                    }
                }
            }
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// Create a pet
    ///
    /// - Remark: HTTP `POST /pets`.
    /// - Remark: Generated from `#/paths//pets/post(createPet)`.
    public enum CreatePet {
        public static let id: Swift.String = "createPet"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/pets/POST/header`.
            public struct Headers: Sendable, Hashable {
                /// A description here.
                ///
                /// - Remark: Generated from `#/paths/pets/POST/header/X-Extra-Arguments`.
                public var xExtraArguments: Components.Schemas.CodeError?
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.CreatePet.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - xExtraArguments: A description here.
                ///   - accept:
                public init(
                    xExtraArguments: Components.Schemas.CodeError? = nil,
                    accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.CreatePet.AcceptableContentType>] = .defaultValues()
                ) {
                    self.xExtraArguments = xExtraArguments
                    self.accept = accept
                }
            }
            public var headers: Operations.CreatePet.Input.Headers
            /// - Remark: Generated from `#/paths/pets/POST/requestBody`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/pets/POST/requestBody/content/application\/json`.
                case json(Components.Schemas.CreatePetRequest)
            }
            public var body: Operations.CreatePet.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            ///   - body:
            public init(
                headers: Operations.CreatePet.Input.Headers = .init(),
                body: Operations.CreatePet.Input.Body
            ) {
                self.headers = headers
                self.body = body
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Created: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/pets/POST/responses/201/headers`.
                public struct Headers: Sendable, Hashable {
                    /// A description here.
                    ///
                    /// - Remark: Generated from `#/paths/pets/POST/responses/201/headers/X-Extra-Arguments`.
                    public var xExtraArguments: Components.Schemas.CodeError?
                    /// Creates a new `Headers`.
                    ///
                    /// - Parameters:
                    ///   - xExtraArguments: A description here.
                    public init(xExtraArguments: Components.Schemas.CodeError? = nil) {
                        self.xExtraArguments = xExtraArguments
                    }
                }
                /// Received HTTP response headers
                public var headers: Operations.CreatePet.Output.Created.Headers
                /// - Remark: Generated from `#/paths/pets/POST/responses/201/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/pets/POST/responses/201/content/application\/json`.
                    case json(Components.Schemas.Pet)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.Pet {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.CreatePet.Output.Created.Body
                /// Creates a new `Created`.
                ///
                /// - Parameters:
                ///   - headers: Received HTTP response headers
                ///   - body: Received HTTP response body
                public init(
                    headers: Operations.CreatePet.Output.Created.Headers = .init(),
                    body: Operations.CreatePet.Output.Created.Body
                ) {
                    self.headers = headers
                    self.body = body
                }
            }
            /// Successfully created pet
            ///
            /// - Remark: Generated from `#/paths//pets/post(createPet)/responses/201`.
            ///
            /// HTTP response code: `201 created`.
            case created(Operations.CreatePet.Output.Created)
            /// The associated value of the enum case if `self` is `.created`.
            ///
            /// - Throws: An error if `self` is not `.created`.
            /// - SeeAlso: `.created`.
            public var created: Operations.CreatePet.Output.Created {
                get throws {
                    switch self {
                    case let .created(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "created",
                            response: self
                        )
                    }
                }
            }
            /// Bad request
            ///
            /// - Remark: Generated from `#/paths//pets/post(createPet)/responses/4XX`.
            ///
            /// HTTP response code: `400...499 clientError`.
            case clientError(statusCode: Swift.Int, Components.Responses.ErrorBadRequest)
            /// The associated value of the enum case if `self` is `.clientError`.
            ///
            /// - Throws: An error if `self` is not `.clientError`.
            /// - SeeAlso: `.clientError`.
            public var clientError: Components.Responses.ErrorBadRequest {
                get throws {
                    switch self {
                    case let .clientError(_, response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "clientError",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// Create a pet using a url form
    ///
    /// - Remark: HTTP `POST /pets/create`.
    /// - Remark: Generated from `#/paths//pets/create/post(createPetWithForm)`.
    public enum CreatePetWithForm {
        public static let id: Swift.String = "createPetWithForm"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/pets/create/POST/requestBody`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/pets/create/POST/requestBody/content/application\/x-www-form-urlencoded`.
                case urlEncodedForm(Components.Schemas.CreatePetRequest)
            }
            public var body: Operations.CreatePetWithForm.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - body:
            public init(body: Operations.CreatePetWithForm.Input.Body) {
                self.body = body
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct NoContent: Sendable, Hashable {
                /// Creates a new `NoContent`.
                public init() {}
            }
            /// Successfully created pet using a url form
            ///
            /// - Remark: Generated from `#/paths//pets/create/post(createPetWithForm)/responses/204`.
            ///
            /// HTTP response code: `204 noContent`.
            case noContent(Operations.CreatePetWithForm.Output.NoContent)
            /// Successfully created pet using a url form
            ///
            /// - Remark: Generated from `#/paths//pets/create/post(createPetWithForm)/responses/204`.
            ///
            /// HTTP response code: `204 noContent`.
            public static var noContent: Self {
                .noContent(.init())
            }
            /// The associated value of the enum case if `self` is `.noContent`.
            ///
            /// - Throws: An error if `self` is not `.noContent`.
            /// - SeeAlso: `.noContent`.
            public var noContent: Operations.CreatePetWithForm.Output.NoContent {
                get throws {
                    switch self {
                    case let .noContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "noContent",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
    }
    /// - Remark: HTTP `GET /pets/stats`.
    /// - Remark: Generated from `#/paths//pets/stats/get(getStats)`.
    public enum GetStats {
        public static let id: Swift.String = "getStats"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/pets/stats/GET/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.GetStats.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.GetStats.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.GetStats.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            public init(headers: Operations.GetStats.Input.Headers = .init()) {
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/pets/stats/GET/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/pets/stats/GET/responses/200/content/application\/json`.
                    case json(Components.Schemas.PetStats)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.PetStats {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            default:
                                try throwUnexpectedResponseBody(
                                    expectedContent: "application/json",
                                    body: self
                                )
                            }
                        }
                    }
                    /// - Remark: Generated from `#/paths/pets/stats/GET/responses/200/content/text\/plain`.
                    case plainText(OpenAPIRuntime.HTTPBody)
                    /// The associated value of the enum case if `self` is `.plainText`.
                    ///
                    /// - Throws: An error if `self` is not `.plainText`.
                    /// - SeeAlso: `.plainText`.
                    public var plainText: OpenAPIRuntime.HTTPBody {
                        get throws {
                            switch self {
                            case let .plainText(body):
                                return body
                            default:
                                try throwUnexpectedResponseBody(
                                    expectedContent: "text/plain",
                                    body: self
                                )
                            }
                        }
                    }
                    /// - Remark: Generated from `#/paths/pets/stats/GET/responses/200/content/application\/octet-stream`.
                    case binary(OpenAPIRuntime.HTTPBody)
                    /// The associated value of the enum case if `self` is `.binary`.
                    ///
                    /// - Throws: An error if `self` is not `.binary`.
                    /// - SeeAlso: `.binary`.
                    public var binary: OpenAPIRuntime.HTTPBody {
                        get throws {
                            switch self {
                            case let .binary(body):
                                return body
                            default:
                                try throwUnexpectedResponseBody(
                                    expectedContent: "application/octet-stream",
                                    body: self
                                )
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.GetStats.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.GetStats.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// A successful response.
            ///
            /// - Remark: Generated from `#/paths//pets/stats/get(getStats)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.GetStats.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.GetStats.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case plainText
            case binary
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                case "text/plain":
                    self = .plainText
                case "application/octet-stream":
                    self = .binary
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                case .plainText:
                    return "text/plain"
                case .binary:
                    return "application/octet-stream"
                }
            }
            public static var allCases: [Self] {
                [
                    .json,
                    .plainText,
                    .binary
                ]
            }
        }
    }
    /// - Remark: HTTP `POST /pets/stats`.
    /// - Remark: Generated from `#/paths//pets/stats/post(postStats)`.
    public enum PostStats {
        public static let id: Swift.String = "postStats"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/pets/stats/POST/requestBody`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/pets/stats/POST/requestBody/content/application\/json`.
                case json(Components.Schemas.PetStats)
                /// - Remark: Generated from `#/paths/pets/stats/POST/requestBody/content/text\/plain`.
                case plainText(OpenAPIRuntime.HTTPBody)
                /// - Remark: Generated from `#/paths/pets/stats/POST/requestBody/content/application\/octet-stream`.
                case binary(OpenAPIRuntime.HTTPBody)
            }
            public var body: Operations.PostStats.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - body:
            public init(body: Operations.PostStats.Input.Body) {
                self.body = body
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Accepted: Sendable, Hashable {
                /// Creates a new `Accepted`.
                public init() {}
            }
            /// Accepted data.
            ///
            /// - Remark: Generated from `#/paths//pets/stats/post(postStats)/responses/202`.
            ///
            /// HTTP response code: `202 accepted`.
            case accepted(Operations.PostStats.Output.Accepted)
            /// Accepted data.
            ///
            /// - Remark: Generated from `#/paths//pets/stats/post(postStats)/responses/202`.
            ///
            /// HTTP response code: `202 accepted`.
            public static var accepted: Self {
                .accepted(.init())
            }
            /// The associated value of the enum case if `self` is `.accepted`.
            ///
            /// - Throws: An error if `self` is not `.accepted`.
            /// - SeeAlso: `.accepted`.
            public var accepted: Operations.PostStats.Output.Accepted {
                get throws {
                    switch self {
                    case let .accepted(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "accepted",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
    }
    /// - Remark: HTTP `POST /probe/`.
    /// - Remark: Generated from `#/paths//probe//post(probe)`.
    public enum Probe {
        public static let id: Swift.String = "probe"
        public struct Input: Sendable, Hashable {
            /// Creates a new `Input`.
            public init() {}
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct NoContent: Sendable, Hashable {
                /// Creates a new `NoContent`.
                public init() {}
            }
            /// Ack
            ///
            /// - Remark: Generated from `#/paths//probe//post(probe)/responses/204`.
            ///
            /// HTTP response code: `204 noContent`.
            case noContent(Operations.Probe.Output.NoContent)
            /// Ack
            ///
            /// - Remark: Generated from `#/paths//probe//post(probe)/responses/204`.
            ///
            /// HTTP response code: `204 noContent`.
            public static var noContent: Self {
                .noContent(.init())
            }
            /// The associated value of the enum case if `self` is `.noContent`.
            ///
            /// - Throws: An error if `self` is not `.noContent`.
            /// - SeeAlso: `.noContent`.
            public var noContent: Operations.Probe.Output.NoContent {
                get throws {
                    switch self {
                    case let .noContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "noContent",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
    }
    /// Update just a specific property of an existing pet. Nothing is updated if no request body is provided.
    ///
    /// - Remark: HTTP `PATCH /pets/{petId}`.
    /// - Remark: Generated from `#/paths//pets/{petId}/patch(updatePet)`.
    public enum UpdatePet {
        public static let id: Swift.String = "updatePet"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/pets/{petId}/PATCH/path`.
            public struct Path: Sendable, Hashable {
                /// Id of the pet
                ///
                /// - Remark: Generated from `#/paths/pets/{petId}/PATCH/path/petId`.
                public var petId: Swift.Int64
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - petId: Id of the pet
                public init(petId: Swift.Int64) {
                    self.petId = petId
                }
            }
            public var path: Operations.UpdatePet.Input.Path
            /// - Remark: Generated from `#/paths/pets/{petId}/PATCH/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.UpdatePet.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.UpdatePet.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.UpdatePet.Input.Headers
            public var body: Components.RequestBodies.UpdatePetRequest?
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - headers:
            ///   - body:
            public init(
                path: Operations.UpdatePet.Input.Path,
                headers: Operations.UpdatePet.Input.Headers = .init(),
                body: Components.RequestBodies.UpdatePetRequest? = nil
            ) {
                self.path = path
                self.headers = headers
                self.body = body
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct NoContent: Sendable, Hashable {
                /// Creates a new `NoContent`.
                public init() {}
            }
            /// Successfully updated
            ///
            /// - Remark: Generated from `#/paths//pets/{petId}/patch(updatePet)/responses/204`.
            ///
            /// HTTP response code: `204 noContent`.
            case noContent(Operations.UpdatePet.Output.NoContent)
            /// Successfully updated
            ///
            /// - Remark: Generated from `#/paths//pets/{petId}/patch(updatePet)/responses/204`.
            ///
            /// HTTP response code: `204 noContent`.
            public static var noContent: Self {
                .noContent(.init())
            }
            /// The associated value of the enum case if `self` is `.noContent`.
            ///
            /// - Throws: An error if `self` is not `.noContent`.
            /// - SeeAlso: `.noContent`.
            public var noContent: Operations.UpdatePet.Output.NoContent {
                get throws {
                    switch self {
                    case let .noContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "noContent",
                            response: self
                        )
                    }
                }
            }
            public struct BadRequest: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/pets/{petId}/PATCH/responses/400/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/pets/{petId}/PATCH/responses/400/content/json`.
                    public struct JsonPayload: Codable, Hashable, Sendable {
                        /// - Remark: Generated from `#/paths/pets/{petId}/PATCH/responses/400/content/json/message`.
                        public var message: Swift.String
                        /// Creates a new `JsonPayload`.
                        ///
                        /// - Parameters:
                        ///   - message:
                        public init(message: Swift.String) {
                            self.message = message
                        }
                        public enum CodingKeys: String, CodingKey {
                            case message
                        }
                    }
                    /// - Remark: Generated from `#/paths/pets/{petId}/PATCH/responses/400/content/application\/json`.
                    case json(Operations.UpdatePet.Output.BadRequest.Body.JsonPayload)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Operations.UpdatePet.Output.BadRequest.Body.JsonPayload {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.UpdatePet.Output.BadRequest.Body
                /// Creates a new `BadRequest`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.UpdatePet.Output.BadRequest.Body) {
                    self.body = body
                }
            }
            /// Update input error
            ///
            /// - Remark: Generated from `#/paths//pets/{petId}/patch(updatePet)/responses/400`.
            ///
            /// HTTP response code: `400 badRequest`.
            case badRequest(Operations.UpdatePet.Output.BadRequest)
            /// The associated value of the enum case if `self` is `.badRequest`.
            ///
            /// - Throws: An error if `self` is not `.badRequest`.
            /// - SeeAlso: `.badRequest`.
            public var badRequest: Operations.UpdatePet.Output.BadRequest {
                get throws {
                    switch self {
                    case let .badRequest(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "badRequest",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// Upload an avatar
    ///
    /// - Remark: HTTP `PUT /pets/{petId}/avatar`.
    /// - Remark: Generated from `#/paths//pets/{petId}/avatar/put(uploadAvatarForPet)`.
    public enum UploadAvatarForPet {
        public static let id: Swift.String = "uploadAvatarForPet"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/pets/{petId}/avatar/PUT/path`.
            public struct Path: Sendable, Hashable {
                /// The id of the pet to retrieve
                ///
                /// - Remark: Generated from `#/paths/pets/{petId}/avatar/PUT/path/petId`.
                public var petId: Components.Parameters.Path_petId
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - petId: The id of the pet to retrieve
                public init(petId: Components.Parameters.Path_petId) {
                    self.petId = petId
                }
            }
            public var path: Operations.UploadAvatarForPet.Input.Path
            /// - Remark: Generated from `#/paths/pets/{petId}/avatar/PUT/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.UploadAvatarForPet.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.UploadAvatarForPet.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.UploadAvatarForPet.Input.Headers
            /// - Remark: Generated from `#/paths/pets/{petId}/avatar/PUT/requestBody`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/pets/{petId}/avatar/PUT/requestBody/content/application\/octet-stream`.
                case binary(OpenAPIRuntime.HTTPBody)
            }
            public var body: Operations.UploadAvatarForPet.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - headers:
            ///   - body:
            public init(
                path: Operations.UploadAvatarForPet.Input.Path,
                headers: Operations.UploadAvatarForPet.Input.Headers = .init(),
                body: Operations.UploadAvatarForPet.Input.Body
            ) {
                self.path = path
                self.headers = headers
                self.body = body
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/pets/{petId}/avatar/PUT/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/pets/{petId}/avatar/PUT/responses/200/content/application\/octet-stream`.
                    case binary(OpenAPIRuntime.HTTPBody)
                    /// The associated value of the enum case if `self` is `.binary`.
                    ///
                    /// - Throws: An error if `self` is not `.binary`.
                    /// - SeeAlso: `.binary`.
                    public var binary: OpenAPIRuntime.HTTPBody {
                        get throws {
                            switch self {
                            case let .binary(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.UploadAvatarForPet.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.UploadAvatarForPet.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Echoes avatar back
            ///
            /// - Remark: Generated from `#/paths//pets/{petId}/avatar/put(uploadAvatarForPet)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.UploadAvatarForPet.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.UploadAvatarForPet.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            public struct PreconditionFailed: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/pets/{petId}/avatar/PUT/responses/412/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/pets/{petId}/avatar/PUT/responses/412/content/application\/json`.
                    case json(Swift.String)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Swift.String {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.UploadAvatarForPet.Output.PreconditionFailed.Body
                /// Creates a new `PreconditionFailed`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.UploadAvatarForPet.Output.PreconditionFailed.Body) {
                    self.body = body
                }
            }
            /// Avatar is not acceptable
            ///
            /// - Remark: Generated from `#/paths//pets/{petId}/avatar/put(uploadAvatarForPet)/responses/412`.
            ///
            /// HTTP response code: `412 preconditionFailed`.
            case preconditionFailed(Operations.UploadAvatarForPet.Output.PreconditionFailed)
            /// The associated value of the enum case if `self` is `.preconditionFailed`.
            ///
            /// - Throws: An error if `self` is not `.preconditionFailed`.
            /// - SeeAlso: `.preconditionFailed`.
            public var preconditionFailed: Operations.UploadAvatarForPet.Output.PreconditionFailed {
                get throws {
                    switch self {
                    case let .preconditionFailed(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "preconditionFailed",
                            response: self
                        )
                    }
                }
            }
            public struct InternalServerError: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/pets/{petId}/avatar/PUT/responses/500/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/pets/{petId}/avatar/PUT/responses/500/content/text\/plain`.
                    case plainText(OpenAPIRuntime.HTTPBody)
                    /// The associated value of the enum case if `self` is `.plainText`.
                    ///
                    /// - Throws: An error if `self` is not `.plainText`.
                    /// - SeeAlso: `.plainText`.
                    public var plainText: OpenAPIRuntime.HTTPBody {
                        get throws {
                            switch self {
                            case let .plainText(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.UploadAvatarForPet.Output.InternalServerError.Body
                /// Creates a new `InternalServerError`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.UploadAvatarForPet.Output.InternalServerError.Body) {
                    self.body = body
                }
            }
            /// Server error
            ///
            /// - Remark: Generated from `#/paths//pets/{petId}/avatar/put(uploadAvatarForPet)/responses/500`.
            ///
            /// HTTP response code: `500 internalServerError`.
            case internalServerError(Operations.UploadAvatarForPet.Output.InternalServerError)
            /// The associated value of the enum case if `self` is `.internalServerError`.
            ///
            /// - Throws: An error if `self` is not `.internalServerError`.
            /// - SeeAlso: `.internalServerError`.
            public var internalServerError: Operations.UploadAvatarForPet.Output.InternalServerError {
                get throws {
                    switch self {
                    case let .internalServerError(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "internalServerError",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case binary
            case json
            case plainText
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/octet-stream":
                    self = .binary
                case "application/json":
                    self = .json
                case "text/plain":
                    self = .plainText
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .binary:
                    return "application/octet-stream"
                case .json:
                    return "application/json"
                case .plainText:
                    return "text/plain"
                }
            }
            public static var allCases: [Self] {
                [
                    .binary,
                    .json,
                    .plainText
                ]
            }
        }
    }
    /// - Remark: HTTP `GET /pets/multipart-typed`.
    /// - Remark: Generated from `#/paths//pets/multipart-typed/get(multipartDownloadTyped)`.
    public enum MultipartDownloadTyped {
        public static let id: Swift.String = "multipartDownloadTyped"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/pets/multipart-typed/GET/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.MultipartDownloadTyped.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.MultipartDownloadTyped.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.MultipartDownloadTyped.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            public init(headers: Operations.MultipartDownloadTyped.Input.Headers = .init()) {
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            /// A typed multipart response.
            ///
            /// - Remark: Generated from `#/paths//pets/multipart-typed/get(multipartDownloadTyped)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Components.Responses.MultipartDownloadTypedResponse)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Components.Responses.MultipartDownloadTypedResponse {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case multipartForm
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "multipart/form-data":
                    self = .multipartForm
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .multipartForm:
                    return "multipart/form-data"
                }
            }
            public static var allCases: [Self] {
                [
                    .multipartForm
                ]
            }
        }
    }
    /// - Remark: HTTP `POST /pets/multipart-typed`.
    /// - Remark: Generated from `#/paths//pets/multipart-typed/post(multipartUploadTyped)`.
    public enum MultipartUploadTyped {
        public static let id: Swift.String = "multipartUploadTyped"
        public struct Input: Sendable, Hashable {
            public var body: Components.RequestBodies.MultipartUploadTypedRequest
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - body:
            public init(body: Components.RequestBodies.MultipartUploadTypedRequest) {
                self.body = body
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Accepted: Sendable, Hashable {
                /// Creates a new `Accepted`.
                public init() {}
            }
            /// Successfully accepted the data.
            ///
            /// - Remark: Generated from `#/paths//pets/multipart-typed/post(multipartUploadTyped)/responses/202`.
            ///
            /// HTTP response code: `202 accepted`.
            case accepted(Operations.MultipartUploadTyped.Output.Accepted)
            /// Successfully accepted the data.
            ///
            /// - Remark: Generated from `#/paths//pets/multipart-typed/post(multipartUploadTyped)/responses/202`.
            ///
            /// HTTP response code: `202 accepted`.
            public static var accepted: Self {
                .accepted(.init())
            }
            /// The associated value of the enum case if `self` is `.accepted`.
            ///
            /// - Throws: An error if `self` is not `.accepted`.
            /// - SeeAlso: `.accepted`.
            public var accepted: Operations.MultipartUploadTyped.Output.Accepted {
                get throws {
                    switch self {
                    case let .accepted(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "accepted",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
    }
}
