// Generated by swift-openapi-generator, do not modify.
#if hasFeature(SourceWarningControl)
@diagnose(UnusedImportAccess, as: ignored) @_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@diagnose(UnusedImportAccess, as: ignored) @preconcurrency public import struct Foundation.URL
@diagnose(UnusedImportAccess, as: ignored) @preconcurrency public import struct Foundation.Data
@diagnose(UnusedImportAccess, as: ignored) @preconcurrency public import struct Foundation.Date
#else
@diagnose(UnusedImportAccess, as: ignored) public import struct Foundation.URL
@diagnose(UnusedImportAccess, as: ignored) public import struct Foundation.Data
@diagnose(UnusedImportAccess, as: ignored) public import struct Foundation.Date
#endif
#else
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
#endif
/// Types generated from the components section of the OpenAPI document.
public enum Components {}
