// Generated by swift-openapi-generator, do not modify.
#if hasFeature(SourceWarningControl)
@diagnose(UnusedImportAccess, as: ignored) @_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@diagnose(UnusedImportAccess, as: ignored) @preconcurrency public import struct Foundation.URL
@diagnose(UnusedImportAccess, as: ignored) @preconcurrency public import struct Foundation.Data
@diagnose(UnusedImportAccess, as: ignored) @preconcurrency public import struct Foundation.Date
#else
@diagnose(UnusedImportAccess, as: ignored) public import struct Foundation.URL
@diagnose(UnusedImportAccess, as: ignored) public import struct Foundation.Data
@diagnose(UnusedImportAccess, as: ignored) public import struct Foundation.Date
#endif
#else
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
#endif
extension Components {
    /// Types generated from the `#/components/parameters` section of the OpenAPI document.
    public enum Parameters {
        /// Supply this parameter to filter pets born since the provided date.
        ///
        /// - Remark: Generated from `#/components/parameters/query.born-since`.
        public typealias Query_bornSince = Components.Schemas.Dob
        /// The id of the pet to retrieve
        ///
        /// - Remark: Generated from `#/components/parameters/path.petId`.
        public typealias Path_petId = Swift.Int64
    }
}
