openapi: '3.1.0'
info:
  title: GreetingService
  version: 1.0.0
servers:
  - url: https://example.com/api
    description: Example service deployment.
components:
  schemas:
    UUID: # this will be replaced by with Foundation.UUID specified by typeOverrides in openapi-generator-config
      type: string
      format: uuid
    
    PrimeNumber: # this will be replaced by with ExternalLibrary.PrimeNumber specified by typeOverrides in openapi-generator-config
      type: string
      format: uuid
      
    User:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        name:
          type: string
        favorite_prime_number:
          $ref: '#/components/schemas/PrimeNumber'
